### PR TITLE
drop heap module

### PR DESCRIPTION
**Pull request by olegrok**
This is really happy case bacause currently we can drop part of
crud module (heap) and replace it with a heap that shipped with
vshard.

Interfaces is not the same but it's easy to fix. Also I want to
note that heap is used for an ancient 1.10 version (that didn't
support tuple-keydef/tuple-merger modules) and 2.2 that has merger
that segfaults. There is no significant benefits to keep our heap
implementation if we could use heap directly from vshard.

### CODE REVIEW

**Comment by ligurio** [comment]
@olegrok, could you rebase to a master branch?

**Review by ligurio — APPROVED** [review]
Thanks for the patch!

Typo in commit message: "beacause" -> "because".

Do we need to mention it in a changelog?

**Comment by ligurio** [comment]
I run performance test that you made in https://github.com/tarantool/crud/pull/196 with patch that increase a readahead buffer (see below) and got following results:

**With proposed patch:** (vshard's heap implementation)

INSERT (Fibers count - 600, Connection count - 10, Timeout  - 30.000000):
1. Requests - 744582, RPS - 24819.400000
2. Requests - 748020, RPS - 24934.000000                                 
3. Requests - 754282, RPS - 25142.733333                                                                                                                                                

SELECT (Fibers count - 200, Connection count - 10, Timeout  - 30.000000)
1. Requests - 104720, RPS - 3490.666667  
2. Requests - 104000, RPS - 3466.666667  
3. Requests - 106060, RPS - 3535.333333  

**Without proposed patch:** (crud's heap implementation)

INSERT (Fibers count - 600, Connection count - 10, Timeout  - 30.000000):
1. Requests - 681047, RPS - 22701.566667                                                                                                                                                 
2. Requests - 712037, RPS - 23734.566667                                                                                                                                                
3. Requests - 702531, RPS - 23417.700000                                                                                                                                                

SELECT (Fibers count - 200, Connection count - 10, Timeout  - 30.000000)
1. Requests - 97340, RPS - 3244.666667
2. Requests - 102120, RPS - 3404.000000 
3. Requests - 98680, RPS - 3289.333333  

```lua
+++ b/test/entrypoint/srv_select.lua
@@ -13,6 +13,12 @@ package.preload['customers-storage'] = function()
     return {
         role_name = 'customers-storage',
         init = function()
+            rawset(_G, 'tarantool_tuning', function()
+                box.cfg{
+                    readahead = 10 * 1024 * 1024,
+                    --wal_mode = 'none',
+                }
+            end)
             local customers_space = box.schema.space.create('customers', {
                 format = {
                     {name = 'id', type = 'unsigned'},
diff --git a/test/performance/select_perf_test.lua b/test/performance/select_perf_test.lua
index 1e73110..6eb4f21 100644
--- a/test/performance/select_perf_test.lua
+++ b/test/performance/select_perf_test.lua
@@ -53,6 +53,11 @@ g.before_all = function()
         },
     })
     g.cluster:start()
+    helpers.call_on_servers(g.cluster, {'s1-master', 's1-replica',
+                                        's2-master', 's2-replica',
+                                        's3-master', 's3-replica'}, function(server)
+        server.net_box:call('tarantool_tuning')
+    end)
 end
 
 g.after_all = function()
```

**Comment by olegrok** [comment]
> Typo in commit message: "beacause" -> "because".

Fixed

> Do we need to mention it in a changelog?

Of course, no. It's not about user-visible changes.

**Pull request merged**
